// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yutaqiddblrtajnglsli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1dGFxaWRkYmxydGFqbmdsc2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTM5NzIsImV4cCI6MjA2MTUyOTk3Mn0.673a9DGEOfEDss5yxLScpTkSPGSgwgPfyHgaeJaQ6jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);